/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:e258c66c-b8eb-4e2d-b4ce-0956f291eec9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ENywQ9s6p",
    "aws_user_pools_web_client_id": "5th1mjtpq7q6knl6v5mp1o7hmr",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://scyy6i2smzh73a3mtj2husz4ja.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ywl6pm72tjagdirykj752xjfky",
    "aws_user_files_s3_bucket": "testinglocal06ec9ce0d3c04d869a228e7fa75f6a8e141236-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
